### ISSUE TITLE
Messing Search Page Background Color

### ISSUE THREAD

**Issue by digomiero** [scriptburn/wp-hide-post#1]
Hi. 
When I try to do a search in my website, and in the results there any hidden pages, the background color goes from white to blue. This blue is present in a lot of CSS customizings across the website, but never as a background as happens in this case.

If I turn off the plugin and try again, then all hidden pages reappear, and the looks of the page goes back to normal.

For testing, go to http://www.meucaovelhinho.com.br
There is a Search box in the header.
Search for "test", and as no pages will be hidden, everything looks fine.
Now search for "curso", which will trigger some hidden pages. Then everything will be blue.

I'm running "Squared" theme by Thrive Themes.

Sorry if I didn't do this the right way. It is the first time I'm sending an issue in GitHub.

BR,

Diego

**Comment by scriptburn** [comment]
HI,

It seems you have some plugin which is interfering with css and adding 

```
<style type="text/css" id="tve_head_custom_css" class="tve_user_custom_style">
body {
                background: #5778b1!important;
            }
</style>
```

so  i would suggest to add this in your functions.php  and see the results

```
add_action('wp_footer', 'scb_enqueue_my_styles');
    function scb_enqueue_my_styles()
    {
        if (is_search())
        {

            echo ('<style type="text/css" >body {background: white; }</style>');

        }
    }
```
