### ISSUE TITLE
conflict

### ISSUE THREAD

**Issue by webtimesaver** [scriptburn/wp-hide-post#2]
Hi,

Updated WP-Hide in WP this morning and found conflict with Mailpoet Plugin - WP-Hide prevented display of the body of content of Mailpoet in the - Settings dashboard (In WP Dashboard). I had to deactivate WP-Hide to enable Mailpoet to display and allow changes.

Reactivated Wp-Hide again afterwards and, when I have time, will review whether previously hidden posts have now become Public as a result of the temporary deactivation, and ? may require reconfiguring.

Do you have a fix for this bug, please?

Best wishes,

Ken

**Comment by scriptburn** [comment]
Can you please post the screenshot with exact url ?
